### ISSUE TITLE
Files write-locked when opened with GUI

### ISSUE THREAD

**Issue by mtCarto** [boundlessgeo/qgis-geogig-plugin#24] opened 2016-04-23 01:01 UTC
This was using the latest qgis-geogig-plugin built from source with GeoGig 1.0-RC2 binaries, and 1.0-RC2 CLI built from src.

When attempting to use the GUI button `Open repoistory in QGIS` Only one repo/branch combo can edit the layer (bikepdx.shp in this case), sometimes none of the repo/branch combos can open it. However, removing the generated shapefile from the repo's directory and exporting the same file via CLI, then using the GUI button to open it works fine and you can make edits. 

This seems to only affect cloned repos and their remote source repo. A new repo with branches (all done via QGIS) did not have this probelm.

Steps to reproduce:
1) Create "master" with 2 branches (alice, bob)  and creating 2 clones (alice, bob) from it, using the CLI as per the current LocationTech GeoGig workshop. [http://workshops.boundlessgeo.com/geogig/workflow/setup.html]
2) Open one of the repo/branches with the GUI button (may be able to edit 1st one)
3) Switch to another repo or branch and open it with the button (unable to edit the layer)

Was a bit tricky to reproduce, I can try to clarify if you can't reproduce.

**Comment by luipir** [comment] 2016-04-23 21:44
@mtCarto can you explain better this phrase:
"This was using the latest qgis-geogig-plugin built from source with GeoGig 1.0-RC2 binaries, and 1.0-RC2 CLI built from src"
Don't you compiled the plugin only with "paver setup"?

**Comment by mtCarto** [comment] 2016-04-25 16:23
@luipir Yes, that is what I meant. I did the setup after pulling the master branch for recent changes. Since , I'm using a VM we setup up a couple months ago for the GeoGig workshop.

**Comment by cuttlefish** [comment] 2016-04-25 23:53
Is there any chance someone will have time to look at this in the next couple of days? We have to do a workshop early next week. This makes it pretty awkward to do the workflow....

**Comment by luipir** [comment] 2016-04-27 07:40
@cuttlefish seems it was an issue with the VM?

tbattle [2:54 AM] 
Well, at least the locking thing seems to be resolved. That was really making me freak out
dblasby [6:51 AM] 
what was causing the locking issue?
tbattle [6:57 AM] 
Tentatively it seems to have been a weird permissions issue caused by the VM that was being used. But seriously, how does either geogig or qgis accidentally run as root?

@cuttlefish and @mtCarto can we close this bug?

**Comment by cuttlefish** [comment] 2016-04-27 08:03
Yeah, it _seems_ to be a weird config issue, although I don't see how it
could happen... Regardless, we should be able to close this after a day or
two of testing.

**Comment by cuttlefish** [comment] 2016-04-27 20:33
Well, haven't come across it again. It seems that it was a weird config issue due to updating the old VM. Closing...

**Closed as completed by cuttlefish** 2016-04-27 20:33 UTC
Labels: bug
